# Generated by Django 6.0.2 on 2026-03-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='symptoms',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
