# Generated by Django 6.0.2 on 2026-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_patient_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            #name='transcript',
            field=models.TextField(blank=True),
        ),
    ]