# Generated by Django 6.0.2 on 2026-03-05 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_auto_20260302_1643'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResultUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='lab_results/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('parsed_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_result_uploads', to='consultations.consultation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_result_uploads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultation', '-created_at'], name='lab_result__consult_744bd3_idx')],
            },
        ),
    ]
