# Generated by Django 6.0.2 on 2026-03-01 21:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom_pattern', models.TextField(db_index=True)),
                ('diagnosis_result', models.JSONField(default=dict)),
                ('success_rating', models.FloatField(default=1.0)),
                ('use_count', models.IntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_memory',
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_id', models.UUIDField(db_index=True)),
                ('agent_type', models.CharField(choices=[('symptom_agent', 'Symptom Agent'), ('diagnosis_agent', 'Diagnosis Agent'), ('lab_agent', 'Lab Agent'), ('controller', 'Controller')], max_length=20)),
                ('input_data', models.JSONField(default=dict, help_text='Input provided to the agent')),
                ('output_data', models.JSONField(default=dict, help_text='Output produced by the agent')),
                ('session_data', models.JSONField(default=dict, help_text='Internal session state')),
                ('tokens_used', models.IntegerField(default=0, help_text='Total tokens used in this session')),
                ('cost', models.DecimalField(decimal_places=6, default=0, help_text='Cost in USD', max_digits=10)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultation_id'], name='agent_sessi_consult_9a796f_idx'), models.Index(fields=['agent_type'], name='agent_sessi_agent_t_902eec_idx'), models.Index(fields=['status'], name='agent_sessi_status_51a545_idx'), models.Index(fields=['created_at'], name='agent_sessi_created_79391a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GPTInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_id', models.UUIDField(db_index=True, null=True)),
                ('model_used', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpt_logs', to='agents.agentsession')),
            ],
            options={
                'db_table': 'gpt_interaction_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultation_id'], name='gpt_interac_consult_132044_idx'), models.Index(fields=['session'], name='gpt_interac_session_e32afb_idx'), models.Index(fields=['created_at'], name='gpt_interac_created_b3b1ec_idx')],
            },
        ),
    ]
