# Generated by Django 6.0.2 on 2026-02-28 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackboardHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_id', models.UUIDField(db_index=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blackboard_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlackboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_id', models.UUIDField(db_index=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_acquired', models.BooleanField(default=False)),
                ('lock_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blackboard_entries',
                'indexes': [models.Index(fields=['consultation_id', '-created_at'], name='blackboard__consult_0edabc_idx'), models.Index(fields=['lock_acquired', 'lock_expires_at'], name='blackboard__lock_ac_1ac69d_idx')],
            },
        ),
    ]
